#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROTO_DIR=$SCRIPT_DIR/../assets/Protobufs
PROTOTS_DIR=$SCRIPT_DIR/../src/protots
MODULE_DIR="$SCRIPT_DIR"/../node_modules/ts-proto/protoc-gen-ts_proto

if cd "$PROTO_DIR"; then git pull; else git clone https://github.com/SteamDatabase/Protobufs $PROTO_DIR; fi
rm -rf "$PROTOTS_DIR" &&
mkdir "$PROTOTS_DIR" &&
cd "$PROTO_DIR"/steam &&
protoc \
	--plugin="$MODULE_DIR" \
	--ts_proto_opt=esModuleInterop=true \
	--ts_proto_opt=env=node \
	--ts_proto_opt=outputEncodeMethods=true \
	--ts_proto_out="$PROTOTS_DIR" \
	--ts_proto_opt=forceLong=string \
	-I="." \
	steammessages_auth.steamclient.proto \
	steammessages_clientserver_login.proto \
	enums_clientserver.proto
